'use client';

import React, { useState, useEffect } from 'react';
import { DragDropContext, Droppable, Draggable } from '@hello-pangea/dnd';
import { X, GripVertical, Plus, Trash2, Save, GripHorizontal } from 'lucide-react';
import axios from 'axios';
import { CRM_GRADIENTS, MAX_STAGES } from '../constants';

const FunnelConfigModal = ({ isOpen, onClose, onSuccess, connectionId, currentStages }) => {
    const [stages, setStages] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (isOpen && currentStages) {
            // Map currentStages (object) to array for editing
            const formattedStages = Object.values(currentStages)
                .sort((a, b) => a.position - b.position)
                .map((stage, index) => ({
                    id: stage.db_id || `temp-${Date.now()}-${index}`, // db_id from backend, or temp
                    name: stage.name,
                    color_key: stage.color_key || 'purple_blue', // Fallback
                    stage_key: stage.id, // 'novo', 'apresentacao'...
                    position: index
                }));
            setStages(formattedStages);
        }
    }, [isOpen, currentStages]);

    const handleDragEnd = (result) => {
        if (!result.destination) return;

        const items = Array.from(stages);
        const [reorderedItem] = items.splice(result.source.index, 1);
        items.splice(result.destination.index, 0, reorderedItem);

        // Update positions
        const updatedItems = items.map((item, index) => ({
            ...item,
            position: index
        }));

        setStages(updatedItems);
    };

    const handleAddStage = () => {
        if (stages.length >= MAX_STAGES) return;

        const newStage = {
            id: `temp-${Date.now()}`,
            name: 'Nova Etapa',
            color_key: 'purple_blue',
            stage_key: null, // Will be generated by backend
            position: stages.length
        };

        setStages([...stages, newStage]);
    };

    const handleDeleteStage = (index) => {
        // Prevent deleting if it's the only stage? Or ask for confirmation?
        // User didn't specify, but deleting a stage with leads is tricky.
        // For here, we just remove from UI list. Backend will handle 'actual' deletion.
        const newStages = stages.filter((_, i) => i !== index);
        setStages(newStages);
    };

    const handleUpdateStage = (index, field, value) => {
        const newStages = [...stages];
        newStages[index] = { ...newStages[index], [field]: value };
        setStages(newStages);
    };

    const handleSave = async () => {
        setLoading(true);
        setError(null);
        try {
            await axios.post('/api/crm/stages', {
                connectionId,
                stages: stages
            });
            onSuccess();
            onClose();
        } catch (err) {
            console.error('Error saving stages:', err);
            const apiError = err.response?.data?.error || 'Erro ao salvar alterações';
            const apiDetails = err.response?.data?.details || '';
            setError(apiDetails ? `${apiError}: ${apiDetails}` : apiError);
        } finally {
            setLoading(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
            <div className="bg-[#1E1E1E] rounded-2xl w-full max-w-2xl max-h-[90vh] flex flex-col border border-[#333]">
                {/* Header */}
                <div className="p-6 border-b border-[#333] flex justify-between items-center">
                    <div>
                        <h2 className="text-xl font-bold text-white">Configurar Funil</h2>
                        <p className="text-gray-400 text-sm mt-1">
                            Personalize as etapas do seu funil (Máx. {MAX_STAGES})
                        </p>
                    </div>
                    <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
                        <X size={24} />
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-6">
                    {error && (
                        <div className="bg-red-500/10 border border-red-500/50 text-red-500 p-3 rounded-lg mb-4 text-sm">
                            {error}
                        </div>
                    )}

                    <DragDropContext onDragEnd={handleDragEnd}>
                        <Droppable droppableId="stages-list">
                            {(provided) => (
                                <div
                                    {...provided.droppableProps}
                                    ref={provided.innerRef}
                                    className="space-y-3"
                                >
                                    {stages.map((stage, index) => (
                                        <Draggable key={stage.id} draggableId={String(stage.id)} index={index}>
                                            {(provided, snapshot) => (
                                                <div
                                                    ref={provided.innerRef}
                                                    {...provided.draggableProps}
                                                    className={`bg-[#2A2A2A] rounded-xl p-4 flex items-center gap-4 border border-transparent group transition-all ${snapshot.isDragging ? 'shadow-xl ring-2 ring-[#00FF99] scale-[1.02] z-50' : 'hover:border-[#333]'
                                                        }`}
                                                >
                                                    {/* Drag Handle */}
                                                    <div
                                                        {...provided.dragHandleProps}
                                                        className="text-gray-500 hover:text-white cursor-grab active:cursor-grabbing"
                                                    >
                                                        <GripVertical size={20} />
                                                    </div>

                                                    {/* Color Picker */}
                                                    <div className="relative">
                                                        <div
                                                            className="w-10 h-10 rounded-lg cursor-pointer hover:ring-2 hover:ring-white/20 transition-all flex items-center justify-center text-xs text-transparent hover:text-white font-bold"
                                                            style={{ background: CRM_GRADIENTS[stage.color_key]?.value || CRM_GRADIENTS['purple_blue'].value }}
                                                            onClick={() => {
                                                                // Very simple inline "dropdown" toggler could be here, 
                                                                // but for simplicity/UX, maybe just cycle or open a popover?
                                                                // Let's do a simple native select overlay for now or a custom popover?
                                                                // Native select with opacity 0 on top is easiest for "modal in modal" complexity avoiding.
                                                            }}
                                                        >
                                                            <div className="absolute inset-0 opacity-0 cursor-pointer">
                                                                <select
                                                                    value={stage.color_key}
                                                                    onChange={(e) => handleUpdateStage(index, 'color_key', e.target.value)}
                                                                    className="w-full h-full cursor-pointer"
                                                                >
                                                                    {Object.entries(CRM_GRADIENTS).map(([key, gradient]) => (
                                                                        <option key={key} value={key}>
                                                                            {gradient.label}
                                                                        </option>
                                                                    ))}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    {/* Name Input */}
                                                    <div className="flex-1">
                                                        <input
                                                            type="text"
                                                            value={stage.name}
                                                            onChange={(e) => handleUpdateStage(index, 'name', e.target.value)}
                                                            className="w-full bg-transparent text-white font-medium focus:outline-none placeholder-gray-500"
                                                            placeholder="Nome da etapa"
                                                            maxLength={30}
                                                        />
                                                    </div>

                                                    {/* Delete */}
                                                    <button
                                                        onClick={() => handleDeleteStage(index)}
                                                        className="text-gray-500 hover:text-red-500 transition-colors p-2 rounded-lg hover:bg-white/5 opacity-0 group-hover:opacity-100"
                                                        title="Excluir etapa"
                                                    >
                                                        <Trash2 size={18} />
                                                    </button>
                                                </div>
                                            )}
                                        </Draggable>
                                    ))}
                                    {provided.placeholder}
                                </div>
                            )}
                        </Droppable>
                    </DragDropContext>

                    {/* Add Button */}
                    {stages.length < MAX_STAGES && (
                        <button
                            onClick={handleAddStage}
                            className="mt-4 w-full py-3 border border-dashed border-[#444] rounded-xl text-gray-400 hover:text-white hover:border-[#00FF99] hover:bg-[#00FF99]/5 transition-all flex items-center justify-center gap-2 font-medium"
                        >
                            <Plus size={20} />
                            Adicionar Nova Etapa
                        </button>
                    )}
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-[#333] flex justify-end gap-3">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 text-gray-400 hover:text-white font-medium transition-colors"
                    >
                        Cancelar
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={loading}
                        className="flex items-center gap-2 px-6 py-2 bg-[#00FF99] text-black font-bold rounded-xl hover:bg-[#00E88C] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {loading ? (
                            <div className="w-5 h-5 border-2 border-black/30 border-t-black rounded-full animate-spin" />
                        ) : (
                            <Save size={18} />
                        )}
                        Salvar Alterações
                    </button>
                </div>
            </div>
        </div>
    );
};

export default FunnelConfigModal;
